import { fsindBlog } from "@/lib/actions/BlogPostAction";
import BlogEditor from "../_components/blog-editor";
import { Blog } from "@/lib/generated/prisma";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog Editor",
  description: "Edit or create blog posts",
};

interface PageProps {
  searchParams: Promise<{ blogId?: string }>;
}

export default async function page({ searchParams }: PageProps) {
  const params = await searchParams;
  const blogId = params.blogId;

  const defaultBlog: Blog = {
    id: "", // Will be generated by Prisma on create
    title: "",
    description: "",
    slug: "",
    coverImage: null,
    content: "",
    seoTitle: null,
    seoDescription: null,
    published: false,
    views: 0,
    authorId: "", // This will be replaced by the actual authorId from session in saveToDB
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const blog = await fsindBlog(blogId);
  return (
    <div className="md:p-6">
      <BlogEditor blogData={blog || defaultBlog} />
    </div>
  );
}
